schema_version = "1.0.0"

id = "pasty"
version = "0.2.0"
name = "Pasty"
tagline = "Paste images from clipboard into Blender"
maintainer = "thanhph111"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/thanhph111/blender-pasty"

# See: https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["3D View", "Material", "Node", "Sequencer"]

blender_version_min = "4.2.0"

license = [
    "SPDX:GPL-3.0-or-later",
]
copyright = [
    "2026 thanhph111",
]

# Optional: add-ons can list which resources they will require:
# * files (for access of any filesystem operations)
# * network (for internet access)
# * clipboard (to read and/or write the system clipboard)
# * camera (to capture photos and videos)
# * microphone (to capture audio)
#
# If using network, remember to also check `bpy.app.online_access`
# https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
#
# For each permission it is important to also specify the reason why it is required.
# Keep this a single short sentence without a period (.) at the end.
# For longer explanations use the documentation or detail page.
#
[permissions]
clipboard = "Copy and paste images to/from the system clipboard"
files = "Load image files and save generated clipboard images"

# Build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
[build]
paths = [
    "LICENSE",
    "README.md",
    "__init__.py",
    "addon/__init__.py",
    "addon/blender_types.py",
    "addon/clipboard.py",
    "addon/image_lookup.py",
    "addon/preferences.py",
    "addon/registration.py",
    "addon/storage.py",
    "addon/areas/__init__.py",
    "addon/areas/sequencer.py",
    "addon/areas/shader_editor.py",
    "addon/areas/view_3d.py",
]
