name: Release Candidate

on:
  push:
    branches: ['release/**']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  candidate:
    name: Verify and package
    uses: ./.github/workflows/_verify.yml
    permissions:
      actions: write
      contents: read
    with:
      artifact_name: pasty-release-package
      checkout_ref: ${{ github.sha }}
      create_checksum: true
      profile: full
